version: '3'
services:
  db:
    build:
      context: ../
      dockerfile: ./src/dockerfile.postgres
    restart: always

  service:
    build:
      context: ../
      dockerfile: ./src/dockerfile.service
    depends_on:
      - db
    links:
      - db:postgres
    volumes:
      - ../movies_admin/config/static:/movies_admin/config/static
    ports:
      - "8000:8000"

  nginx:
    restart: always
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d
      - ../movies_admin/config/static:/static
    depends_on:
      - service
    ports:
      - "80:80"


networks:
  default:
    external: true
    name: my_network
