FROM python:latest

COPY ./movies_admin/config/settings/requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

COPY ./movies_admin /movies_admin/

WORKDIR /movies_admin/
CMD python ./manage.py collectstatic --noinput; \
gunicorn --bind 0.0.0.0:8000 config.wsgi